server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: test1_route
        uri: https://www.baidu.com
        predicates:
        - Query=url,baidu

      - id: test2_route
        uri: https://www.qq.com
        predicates:
        - Query=url,qq

      - id: product_route
        uri: lb://gulimall-product
        predicates:
        - Path=/api/product/**
        filters:
        - RewritePath=/api/(?<segment>.*),/$\{segment}

      - id: third_party_route
        uri: lb://gulimall-third-party
        predicates:
        - Path=/api/thirdparty/**
        filters:
        - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
        - Path=/api/**
        filters:
          - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


# 按照规则，url=baidu则转发到www.baidu.com；并且Query断言可以是正则表达式
# http://localhost:88/hello?url=qq 解析：1、按照规则转发到https://www.qq.com/hello
# filters 设置网关转发规则：带负载均衡的，路径匹配转发规则，重写路径去掉api，加上/renren-fast

##前端项目，/api
##http://LocaLhost:88/api/captcha.jpg                 http://Localhost:8080/renren-fast/captcha.jpg
##http://LocaLhost:88/api/product/category/list/tree  http://Localhost:10000/product/category/list/tree

  application:
    name: gulimall-gateway
