server:
  port: 30010

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    port: 6379
    host: 192.168.56.10

  session:
    store-type: redis

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10



